package com.secureguard.anticheat;

import java.util.UUID;

public record MovementFrame(
        UUID uuid,
        String playerName,
        double x,
        double y,
        double z,
        double dx,
        double dy,
        double dz,
        double velocityX,
        double velocityY,
        double velocityZ,
        float yaw,
        float pitch,
        double horizontalDistance,
        double movementSpeed,
        double friction,
        double fallDistance,
        double fallDistanceBeforeLanding,
        double health,
        int ping,
        int movementPacketsPerSecond,
        int airTicks,
        double tps,
        boolean onGround,
        boolean wasOnGround,
        boolean creative,
        boolean spectator,
        boolean fallFlying,
        boolean vehicle,
        boolean swimming,
        boolean water,
        boolean lava,
        boolean climbing,
        boolean levitating,
        boolean slowFalling,
        boolean sprinting,
        boolean collisionFree,
        boolean inGrace,
        boolean teleportGrace,
        boolean velocityGrace,
        boolean landedWithoutDamage,
        boolean velocityMismatch
) { }